### ISSUE TITLE
Crashing while deploying on heroku

### ISSUE THREAD

**Issue by daniyallko** [Appeza/MirLeech-Telegram#22]
### Describe the Bug

The bot is not deploying on heroku due to a missing module named 'quoters' 

### Add Logs

2022-01-12T17:11:30.956059+00:00 app[web.1]: Traceback (most recent call last):
2022-01-12T17:11:30.956063+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2022-01-12T17:11:30.956064+00:00 app[web.1]:     return _run_code(code, main_globals, None,
2022-01-12T17:11:30.956065+00:00 app[web.1]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2022-01-12T17:11:30.956066+00:00 app[web.1]:     exec(code, run_globals)
2022-01-12T17:11:30.956066+00:00 app[web.1]:   File "/usr/src/app/bot/__main__.py", line 12, in <module>
2022-01-12T17:11:30.956066+00:00 app[web.1]:     from quoters import Quote
2022-01-12T17:11:30.956067+00:00 app[web.1]: ModuleNotFoundError: No module named 'quoters'
2022-01-12T17:12:04.836546+00:00 heroku[web.1]: Process exited with status 1
2022-01-12T17:12:04.906034+00:00 heroku[web.1]: State changed from up to crashed

### Additional info

I have deployed the bot using github actions and imported the repo into a private repo

**Comment by wrecker3000** [comment]
Fork the repo and edit requirements.txt...write quoters there and deploy
